# Generated by Django 5.2.4 on 2025-08-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('courseDesc', models.TextField()),
                ('courseDuration', models.CharField(max_length=20)),
                ('coursePrice', models.CharField(max_length=30)),
                ('startDate', models.DateField()),
                ('schedule', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('requirements', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
