# Generated by Django 5.2.4 on 2025-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.FileField(upload_to='booked'),
        ),
    ]
